## Import

In [1]:
from heart_stroke_prediction.analyze.feature_selection.wrapper_methods import Wrapper_Methods
from sklearn.model_selection import train_test_split
import pandas as pd
import cloudpickle
from pathlib import Path
import os

from sklearn import set_config
# Set global configuration to output Pandas DataFrames
set_config(transform_output="pandas")

import warnings
warnings.filterwarnings('ignore')

## 1. Read Data

In [2]:
os.getcwd()

'/Users/rahulshelke/Documents/Data-Science/Data-Science-Projects/heart-stroke-prediction'

In [3]:
INPUT_DATA_DIR = os.path.join(os.getcwd(), "notebooks", "data")
INPUT_ARTIFACT_DIR = os.path.join(os.getcwd(), "notebooks", "artifact")

In [4]:
INPUT_DIR = {
    'data': INPUT_DATA_DIR,
    'data_correct': INPUT_ARTIFACT_DIR,
    'handle_missing': INPUT_ARTIFACT_DIR,
    'handle_missing_val': INPUT_ARTIFACT_DIR,
    'handle_outlier': INPUT_ARTIFACT_DIR,
    'engineering_pipeline': INPUT_ARTIFACT_DIR
}

In [5]:
DATA_FILE_NAME = {
    'raw': Path(INPUT_DIR['data'], 'healthcare-dataset-stroke-data.csv'),
    'clean': Path(INPUT_DIR['data_correct'], 'heart_stroke_data.csv'),
}

ARTIFACT_FILE_NAME = {
    'data_correct': Path(INPUT_DIR['data_correct'], 'data_correction_pipeline.pkl'),
    'handle_missing': Path(INPUT_DIR['handle_missing'], 'missing_imputer_pipeline.pkl'),
    'handle_missing_val': Path(INPUT_DIR['handle_missing_val'], 'missing_imputer_validation_pipeline.pkl'),
    'handle_outlier': Path(INPUT_DIR['handle_outlier'], 'outlier_handler_pipeline.pkl'),
    'engineering_pipeline': Path(INPUT_DIR['engineering_pipeline'], 'feature_engineering_pipeline.pkl'),
}

In [6]:
DATA_FILE_NAME

{'raw': PosixPath('/Users/rahulshelke/Documents/Data-Science/Data-Science-Projects/heart-stroke-prediction/notebooks/data/healthcare-dataset-stroke-data.csv'),
 'clean': PosixPath('/Users/rahulshelke/Documents/Data-Science/Data-Science-Projects/heart-stroke-prediction/notebooks/artifact/heart_stroke_data.csv')}

In [7]:
ARTIFACT_FILE_NAME

{'data_correct': PosixPath('/Users/rahulshelke/Documents/Data-Science/Data-Science-Projects/heart-stroke-prediction/notebooks/artifact/data_correction_pipeline.pkl'),
 'handle_missing': PosixPath('/Users/rahulshelke/Documents/Data-Science/Data-Science-Projects/heart-stroke-prediction/notebooks/artifact/missing_imputer_pipeline.pkl'),
 'handle_missing_val': PosixPath('/Users/rahulshelke/Documents/Data-Science/Data-Science-Projects/heart-stroke-prediction/notebooks/artifact/missing_imputer_validation_pipeline.pkl'),
 'handle_outlier': PosixPath('/Users/rahulshelke/Documents/Data-Science/Data-Science-Projects/heart-stroke-prediction/notebooks/artifact/outlier_handler_pipeline.pkl'),
 'engineering_pipeline': PosixPath('/Users/rahulshelke/Documents/Data-Science/Data-Science-Projects/heart-stroke-prediction/notebooks/artifact/feature_engineering_pipeline.pkl')}

## **2. Static Pipeline**

In [8]:
with open(ARTIFACT_FILE_NAME["data_correct"], "rb") as f:
    static_pipeline = cloudpickle.load(f)

In [9]:
static_pipeline

Pipeline(steps=[('correct_column_names',
                 ColumnNameCorrector(mapping={'Residence_type': 'residence_type'})),
                ('correct_column_values',
                 ValueCorrector(column_mappings={'ever_married': {'No': 'no',
                                                                  'Yes': 'yes'},
                                                 'gender': {'Female': 'female',
                                                            'Male': 'male',
                                                            'Other': 'other'},
                                                 'residence_type': {'Rural': 'rural',
                                                                    'Urban': 'urban'},
                                                 'smoking_status': {'Unknown': 'unknown',
                                                                    'formerly smoked': 'formerly_smoked',
                                                                    'never smoked': 'never_smoked'},
                                                 'work_type': {'Govt_job': 'govt_job',
                                                               'Never_worked': 'never_worked',
                                                               'Private': 'private',
                                                               'children': 'children',
                                                               'self-employed': 'self_employed'}})),
                ('missing_normalizer',
                 MissingValueNormalizer(missing_tokens=['unknown'])),
                ('frequency_filter', FrequencyFilter())])

## **3. Read Data**

In [10]:
df = pd.read_csv(DATA_FILE_NAME['raw'])
df = static_pipeline.fit_transform(df)

In [11]:
df.shape

(5109, 12)

In [12]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,male,67.0,0,1,yes,private,urban,228.69,36.6,formerly_smoked,1
1,51676,female,61.0,0,0,yes,self_employed,rural,202.21,NaN,never_smoked,1
2,31112,male,80.0,0,1,yes,private,rural,105.92,32.5,never_smoked,1
3,60182,female,49.0,0,0,yes,private,urban,171.23,34.4,smokes,1
4,1665,female,79.0,1,0,yes,self_employed,rural,174.12,24.0,never_smoked,1

In [13]:
df.isna().sum()

id                      0
gender                  0
age                     0
hypertension            0
heart_disease           0
ever_married            0
work_type               0
residence_type          0
avg_glucose_level       0
bmi                   201
smoking_status       1544
stroke                  0
dtype: int64

In [14]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='str')

## **4. Column Seperation**

In [15]:
TARGET_COL = ['stroke']
ID_COL = ['id']
NUM_FEATURES = ['age', 'bmi', 'avg_glucose_level']
CAT_FEATURES = [ 'gender', 'ever_married', 'work_type', 'residence_type', 'smoking_status', 'hypertension', 'heart_disease']

## **5. Dynamic Pipeline**

In [16]:
with open(ARTIFACT_FILE_NAME["engineering_pipeline"], "rb") as f:
    preprocessor = cloudpickle.load(f)

In [17]:
preprocessor

Pipeline(steps=[('impute_missing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  Pipeline(steps=[('cat_imputer',
                                                                   SimpleImputer(add_indicator=True,
                                                                                 fill_value='missing',
                                                                                 strategy='constant'))]),
                                                  ['work_type',
                                                   'smoking_status', 'gender',
                                                   'ever_married',
                                                   'residence_type']),
                                                 ('num',
                                                  Pipeline(steps=[('num_imputer',
                                                                   SimpleImputer(add_indicator=True,...
                                   verbose_feature_names_out=False)),
                ('encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encode_cat',
                                                  OneHotEncoder(drop='if_binary',
                                                                handle_unknown='ignore',
                                                                min_frequency=5,
                                                                sparse_output=False),
                                                  ['gender', 'ever_married',
                                                   'residence_type',
                                                   'work_type',
                                                   'smoking_status',
                                                   'missingindicator_smoking_status'])],
                                   verbose_feature_names_out=False))])

In [18]:
# feature_engineering_pipeline = joblib.load(os.path.join(ARTIFACT_PATH, "feature_engineering_pipeline_v1.pkl"))
df_composed = preprocessor.fit_transform(df)
df_composed[TARGET_COL] = df[TARGET_COL]

In [19]:
df_composed.head()

,gender_male,ever_married_yes,residence_type_urban,work_type_children,work_type_govt_job,work_type_never_worked,work_type_private,work_type_self_employed,smoking_status_formerly_smoked,smoking_status_missing,...,bmi_age_ratio,avg_glucose_bmi_ratio,age_sqrt,bmi_sqrt,avg_glucose_level_sqrt,hypertension,heart_disease,age,missingindicator_bmi,stroke
0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.546269,8370.054,8.185353,6.049793,15.122500,0,1,67.0,0.0,1
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.460656,5682.101,7.810250,5.300943,14.220056,0,0,61.0,1.0,1
2,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.406250,3442.400,8.944272,5.700877,10.291744,0,1,80.0,0.0,1
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.702041,5890.312,7.000000,5.865151,13.085488,0,0,49.0,0.0,1
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.303797,4178.880,8.888194,4.898979,13.195454,1,0,79.0,0.0,1

In [20]:
df_composed.columns

Index(['gender_male', 'ever_married_yes', 'residence_type_urban',
       'work_type_children', 'work_type_govt_job', 'work_type_never_worked',
       'work_type_private', 'work_type_self_employed',
       'smoking_status_formerly_smoked', 'smoking_status_missing',
       'smoking_status_never_smoked', 'smoking_status_smokes',
       'missingindicator_smoking_status_True', 'bmi', 'avg_glucose_level',
       'bmi_health_category', 'glucose_health_category',
       'age_avg_glucose_interaction', 'age_bmi_interaction', 'bmi_age_ratio',
       'avg_glucose_bmi_ratio', 'age_sqrt', 'bmi_sqrt',
       'avg_glucose_level_sqrt', 'hypertension', 'heart_disease', 'age',
       'missingindicator_bmi', 'stroke'],
      dtype='str')

In [21]:
df_composed.shape

(5109, 29)

## **6. Feature Set**

In [22]:
# NUM_FEATURES = ['bmi', 'avg_glucose_level','age_avg_glucose_interaction', 'age_bmi_interaction', 'bmi_age_ratio',
#                 'avg_glucose_bmi_ratio', 'age_sqrt', 'bmi_sqrt', 'avg_glucose_level_sqrt','age', 'missingindicator_bmi']
# CAT_FEATURES = ['gender_male', 'ever_married_yes', 'residence_type_urban',
#                 'work_type_children', 'work_type_govt_job', 'work_type_never_worked',
#                 'work_type_private', 'work_type_self_employed',
#                 'smoking_status_formerly_smoked', 'smoking_status_missing',
#                 'smoking_status_never_smoked', 'smoking_status_smokes',
#                 'missingindicator_smoking_status_True', 'bmi_health_category', 
#                 'glucose_health_category','hypertension', 'heart_disease',]

In [23]:
# feat = ['age_avg_glucose_interaction', 'age_bmi_interaction', 'bmi_age_ratio', 'avg_glucose_bmi_ratio', 'age_sqrt', 'bmi_sqrt', 'avg_glucose_level_sqrt', 'missingindicator_bmi', 'gender_male', 'ever_married_yes', 'residence_type_urban', 'work_type_children', 'work_type_govt_job', 'work_type_never_worked', 'work_type_private', 'work_type_self_employed', 'smoking_status_formerly_smoked', 'smoking_status_missing', 'smoking_status_never_smoked', 'smoking_status_smokes', 'missingindicator_smoking_status_True', 'bmi_health_category', 'glucose_health_category']

In [24]:
features = NUM_FEATURES + CAT_FEATURES + TARGET_COL #+ feat

# Feature Selection Method : Wrapper Method

In [25]:
df = static_pipeline.fit_transform(pd.read_csv(DATA_FILE_NAME['raw']))

In [26]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,male,67.0,0,1,yes,private,urban,228.69,36.6,formerly_smoked,1
1,51676,female,61.0,0,0,yes,self_employed,rural,202.21,NaN,never_smoked,1
2,31112,male,80.0,0,1,yes,private,rural,105.92,32.5,never_smoked,1
3,60182,female,49.0,0,0,yes,private,urban,171.23,34.4,smokes,1
4,1665,female,79.0,1,0,yes,self_employed,rural,174.12,24.0,never_smoked,1

In [27]:
_, pos_case = train_test_split(df, test_size=0.20, stratify=df['stroke']) # positive cases
neg_case, _ = train_test_split(df, test_size=0.989, stratify=df['stroke']) # negative cases

In [28]:
pos_case.shape, neg_case.shape

((1022, 12), (56, 12))

In [29]:
neg_case['stroke'].value_counts()

stroke
0    53
1     3
Name: count, dtype: int64

In [30]:
test = pd.concat([pos_case[pos_case['stroke'] == 1], neg_case[neg_case['stroke'] == 0]])

In [31]:
params = {
    "df": test,
    "features" : ID_COL+TARGET_COL+NUM_FEATURES+CAT_FEATURES,
    "target" : TARGET_COL,
    "preprocessor": preprocessor,
    "scaler_type": "standard",
    "model_type": "classification",
    "shuffle": True,
    "n_splits": 5,
    "n_repeats": 5,
    "seed": 42,
    "bins": 10,
}

In [32]:
model_config = {"LR": {"max_iter": 1000}}

In [33]:
wm = Wrapper_Methods(**params)

In [34]:
model_report = wm.directional_feature_selection(
    model_configs=model_config
)

Sequential Feature Selection Execution time: 92.94107794761658 seconds
=============== Logistic Regression ===============
Selected Fetaures: ['gender_male', 'ever_married_yes', 'residence_type_urban', 'work_type_govt_job', 'work_type_infrequent_sklearn', 'smoking_status_missing', 'smoking_status_never_smoked', 'missingindicator_smoking_status_True', 'bmi_health_category', 'bmi_age_ratio', 'age_sqrt', 'avg_glucose_level_sqrt', 'hypertension']

roc_auc: 0.7442 (0.0741)
pr_auc: 0.7170 (0.0785)
recall_10: 0.2133 (0.0499)
recall_15: 0.2533 (0.0499)
recall_20: 0.3200 (0.0499)
precision_10: 0.8000 (0.1871)
nns_10: 1.3333 (0.3651)

In [35]:
model_report = wm.directional_feature_selection(
    model_configs=model_config,
    direction="backward"
)

Sequential Feature Selection Execution time: 89.84297704696655 seconds
=============== Logistic Regression ===============
Selected Fetaures: ['work_type_infrequent_sklearn', 'smoking_status_never_smoked', 'glucose_health_category', 'age_avg_glucose_interaction', 'age_bmi_interaction', 'bmi_age_ratio', 'avg_glucose_bmi_ratio', 'age_sqrt', 'bmi_sqrt', 'avg_glucose_level_sqrt', 'hypertension', 'heart_disease', 'age', 'missingindicator_bmi']

roc_auc: 0.7508 (0.0553)
pr_auc: 0.6977 (0.0663)
recall_10: 0.1733 (0.0533)
recall_15: 0.2133 (0.0267)
recall_20: 0.3067 (0.0327)
precision_10: 0.6500 (0.2000)
nns_10: 1.6667 (0.4216)

In [36]:
wm.backward_feature_elimination(
    model_configs=model_config
)

TypeError: Wrapper_Methods.classfier_for_imbalanced_data() missing 1 required positional argument: 'direction'